
    - name: Setup project pkgset
      replace: dest=~/.gvm/environments/{{ go_version }}@{{ pkgset }} regexp="{{ item.regex }}" replace="{{ item.replacement }}"
      with_items:
      - {regex: '\$GOPATH', replacement: '$HOME/go:$GOPATH'}
      - {regex: '\${GVM_OVERLAY_PREFIX}\/bin\:\${PATH}', replacement: '${GVM_OVERLAY_PREFIX}/bin:$HOME/go/bin:${PATH}'}

    - name: Set project pkgset as default
      shell: bash -l -c "gvm pkgset use {{ pkgset }} --default"
